import { DomainName, DomainStatus } from "../value_object"

export class Domain {
    // serial number for the domain, generated by the database
    id: number
    // the domain name to be verified
    domain: DomainName
    // the ID of the owner of the domain, which can be used to link to a User entity in the future
    owner_id: number
    
    // the status of the domain verification process, which can be PENDING, VERIFIED, or FAILED
    status: DomainStatus
    // timestamps for when the domain was created and last updated
    createdAt: Date
    // the timestamp for when the domain was last updated, which can be used to track the verification process and determine if a domain has expired
    updatedAt: Date

    constructor(
        id: number,
        domain: DomainName,
        owner_id: number,
        status: DomainStatus,
        createdAt: Date,
        updatedAt: Date
    ) {
        this.id = id
        this.domain = domain
        this.owner_id = owner_id
        this.status = status
        this.createdAt = createdAt
        this.updatedAt = updatedAt
    }

    /**
     * Factory method to create a new Domain instance.
     * The id will be generated by the database, so it is set to 0 for now.
     * The status is set to PENDING.
     * The createdAt and updatedAt fields are set to the current date and time.
     * 
     * @param domain The domain name to be verified.
     * @param owner_id The ID of the owner of the domain.
     * @returns A new instance of the Domain class with the provided domain and owner, and other fields initialized accordingly.
     */
    static create(domain: DomainName, owner_id: number): Domain {
        const now = new Date()
        // the id will be generated by the database, so we can set it to 0 for now
        return new Domain(0, domain, owner_id, DomainStatus.PENDING, now, now)
    }

    setStatus(status: DomainStatus) {
        this.status = status
        this.updatedAt = new Date()
    }
}